run:
  deadline: 5m
  skip-dirs:
    - app
    - cmd
    - config
    - system
    - ui
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustruct
    - varnamelen
    - gochecknoinits
    - wrapcheck
    - execinquery
    - funlen
    # generics disabled
    - wastedassign
    - rowserrcheck
    # deprecated
    - nosnakecase
    - varcheck
    - structcheck
    - ifshort
    - deadcode
    - golint
    - maligned
    - interfacer
    - scopelint
    - exhaustivestruct
    - gomoddirectives
linters-settings:
  errcheck:
    check-blank: false
    ignore: fmt:.*
  nolintlint:
    require-specific: true
