run:
  deadline: 5m
  skip-files:
    - ".*_test.go"
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustruct
    - varnamelen
    - gochecknoinits
    - wrapcheck
    - execinquery
    - funlen
    # generics disabled
    - wastedassign
    - rowserrcheck
    # deprecated
    - nosnakecase
    - varcheck
    - structcheck
    - ifshort
    - deadcode
    - golint
    - maligned
    - interfacer
    - scopelint
    - exhaustivestruct
    - gomoddirectives
linters-settings:
#  typecheck:
#    enabled: false
  errcheck:
    check-blank: false
    ignore: fmt:.*
  nolintlint:
    require-specific: true
