# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: podman-tui.spec

jobs:
  - job: copr_build
    trigger: pull_request
    enable_net: true
    srpm_build_deps:
      - make
      - openssl-devel
      - rpkg
    targets:
      - fedora-latest-stable
      - fedora-development
      # Disabled until there is go 1.22.6 in centos stream
      #- epel-9-x86_64
      #- epel-9-aarch64
      #- centos-stream-9-x86_64
      #- centos-stream-9-aarch64
      #- centos-stream-10-x86_64
      #- centos-stream-10-aarch64
    actions:
      post-upstream-clone:
        - "rpkg spec --outdir ./"

      fix-spec-file:
        "bash .packit.sh"
